### ISSUE TITLE
Wrap up migration to github

### ISSUE THREAD

**Issue by wcravens** [wcravens/openrocket#1]
Known issues remaining:
- [x] **Static information pages** ( #2 ) e.g. Marketing, Tutorial, and Developer Engagement documents
- [ ] **Dynamic pages** e.g. 'Live update checking' and bug reports. (https://github.com/openrocket/openrocket/issues/260)
- [x] **Hosting of Binaries**  ( #3 )
- [ ] **Build and DevOps**\- [HTML Proofer CI with Travis](http://jekyllrb.com/docs/continuous-integration/)
- [ ] **Coordinate the move of the Thesis** ( #4 )
